"""Add daily checkins table

Revision ID: 4e2296adb942
Revises: 74df08c5d55a
Create Date: 2025-10-04 12:46:53.526279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4e2296adb942'
down_revision: Union[str, Sequence[str], None] = '74df08c5d55a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_checkins',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('hrv', sa.Integer(), nullable=True),
    sa.Column('rhr', sa.Integer(), nullable=True),
    sa.Column('sleep_hours', sa.Integer(), nullable=True),
    sa.Column('sleep_quality', sa.Integer(), nullable=True),
    sa.Column('soreness_level', sa.Integer(), nullable=True),
    sa.Column('soreness_areas', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('energy_level', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('date IS NOT NULL', name='date_not_null'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('daily_checkins')
    # ### end Alembic commands ###
