"""Add user profiles table

Revision ID: 5f50a9d2d284
Revises: 2c20e2f768f2
Create Date: 2025-10-05 15:00:05.956079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5f50a9d2d284'
down_revision: Union[str, Sequence[str], None] = '2c20e2f768f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('badminton_days', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('primary_sport', sa.String(length=50), nullable=True),
    sa.Column('running_goal', sa.Text(), nullable=True),
    sa.Column('weekly_run_volume_target', sa.Integer(), nullable=True),
    sa.Column('current_injuries', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('injury_history', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_profiles')
    # ### end Alembic commands ###
